print("1a. Las máquinas me sorprenden con mucha frecuencia.")
print()
print("1c. Let it roll, baby, roll.")
print("1d. Ocurrio un error de sintaxis")
print('1e. Una computadora puede ser llamada "inteligente" si logra engañar a una persona haciéndole creer que es un humano.')
print("1f. Nombre: Maximiliano")
print("Apellido: Alvarez")
print("Edad: 21")
print("1g. Nombre:","Maximiliano","Apellido:","Alvarez","Edad:","21",sep="_")
print("1h. Calle: Belgrano\t Numero: 325\t Codigo Postal: 9400")
print("1i. Calle: Belgrano\n Numero: 325\n Codigo Postal: 9400")
print("1k. ")
print("     *")
print("    * *")
print("   *   *")
print("  *     *")
print(" ***   ***")
print("   *   *")
print("   *   *")
print("   *****")